# Two server blocks on port 8080 with different server_names
server {
    listen 127.0.0.1:8080;
    server_name one.example.com;
    client_max_body_size 150M;

    location / {
        limit_except GET
        root www;
        autoindex off;
        index index.html;
    }

    location /testdir {
        limit_except GET
        root www/testdir;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name two.example.com;
    client_max_body_size 150M;

    location / {
        limit_except GET
        root www;
        autoindex off;
        index index2.html;
    }
}

# A second port with its own server
server {
    listen 127.0.0.1:8081;
    server_name three.example.com;
    client_max_body_size 150M;

    location / {
        limit_except GET
        root www;
        autoindex off;
        index index.html;
    }

    location /uploads {
        limit_except GET POST DELETE
        root uploads;
        autoindex on;
        upload uploads;
    }
}
